const terms = {
    carreira: [
        'carreira',
        'conectar',
        'time',
        'nosso',
        'vagas',
        'desenvolvedor',
        'designer',
        'banco',
        'talento',
        'talentos',
        'inscreva-se'
    ],
    case: [
        'case',
        'cases',
        'nubank',
        'vivo',
        'alelo',
        'ifood',
        'sobre',
        'experiência',
        'sucesso',
        'tecnologia',
        'parceiros',
        'parceiro',
        'parceiras',
        'parceiros',
        'ler',
        'completo',
        'sucesso'
    ],
    cases: [
        'cases',
        'cases',
        'experiência',
        'sucesso',
        'tecnologia',
        'parceiros',
        'parceiro',
        'parceiras',
        'parceiros',
        'ler',
        'completo',
        'sucesso',
    ],
    contato: [
        'contato',
        'detalhes',
        'fale',
        'conosco',
        'entrar',
        'mensagem',
        'endereço',
        'mapa',
    ],
    parceiros: [
        'parceiros',
        'parceiro',
        'parceiras',
        'parceira',
        'reconhecidos',
        'reconhecido',
        'curadoria',
        'projeto',
        'implantar',
        'nuvem',
        'teste',
        'produção',
        'gerenciar',
        'solace',
        'solvo',
        'wib'

    ],
    servicos: [
        'serviços',
        'serviço',
        'habilidades',
        'habilidade',
        'aplicações',
        'exemplos',
        'projeto',
        'implantar',
        'nuvem',
        'teste',
        'produção',
        'gerenciar',
    ],
    sobre: [
        'sobre',
        'projeto',
        'implantar',
        'nuvem',
        'teste',
        'produção',
        'gerenciar',
        'solução',
        'soluções',
        'digitais',
        'parceiros',
        'desenvolvedores',
        'equipe',
        'qualidade',
        'parceria',
        'conhecimento',
        'certificados',
        'certificado',
        'vagas',
        'consultores',
        'objetivo'
    ],
}

export default terms;